apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-local-tls
  namespace: elasticsearch
spec:
  secretName: elasticsearch-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - search.suma-honda.local
