apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suma-android.fullname" . }}
  namespace: {{ .Values.namespace | default "suma-android" }}
  labels:
    {{- include "suma-android.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "suma-android.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "suma-android.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: {{ .Values.command | default (list "php" "artisan" "serve" "--host=0.0.0.0" "--port=8000") | toJson }}
        workingDir: {{ .Values.workingDir | default "/var/www/html" }}
        ports:
        - containerPort: {{ .Values.service.port | default 8000 }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.service.port | default 8000 }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds | default 10 }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold | default 30 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port | default 8000 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 60 }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port | default 8000 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        {{- range .Values.persistence.volumes }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      {{- range .Values.persistence.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ include "suma-android.fullname" $ }}-{{ .name }}
      {{- end }}
      {{- end }}
