apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: suma-webhook-local
      namespace: suma-webhook
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "10m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    spec:
      ingressClassName: nginx
      tls:
        - hosts:
            - webhook.suma-honda.local
          secretName: suma-webhook-tls
      rules:
        - host: webhook.suma-honda.local
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: suma-webhook
                    port:
                      number: 80
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: suma-webhook-api
      namespace: suma-webhook
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        nginx.ingress.kubernetes.io/proxy-body-size: "10m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
    spec:
      ingressClassName: nginx
      tls:
        - hosts:
            - api.suma-honda.id
          secretName: api-suma-honda-id-tls
      rules:
        - host: api.suma-honda.id
          http:
            paths:
              - path: /suma-webhook(/|$)(.*)
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: suma-webhook
                    port:
                      number: 80