# Common Settings
nameOverride: ""
fullnameOverride: ""

# Prometheus Configuration
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.45.0
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  persistence:
    enabled: false  # Disabled for dev - using emptyDir
  
  retention: 15d
  scrapeInterval: 15s
  
  service:
    type: ClusterIP
    port: 9090
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: prometheus.suma-honda.id
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.suma-honda.id

# Grafana Configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 10.1.0
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  persistence:
    enabled: false  # Disabled for dev - using emptyDir
  
  adminUser: admin
  adminPassword: admin  # Change in production
  
  service:
    type: ClusterIP
    port: 3000
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: grafana.suma-honda.id
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.suma-honda.id

# AlertManager Configuration
alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: v0.25.0
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  persistence:
    enabled: false  # Disabled for dev - using emptyDir
  
  service:
    type: ClusterIP
    port: 9093
  
  ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
      - host: alertmanager.suma-honda.id
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.suma-honda.id

# Loki Configuration (optional for log aggregation)
loki:
  enabled: false  # Disable by default for dev
  service:
    type: ClusterIP
    port: 3100

# Blackbox Exporter Configuration (optional for endpoint monitoring)
blackboxExporter:
  enabled: false  # Disable by default for dev
  service:
    type: ClusterIP
    port: 9115

# Node Exporter Configuration (optional for node metrics)
nodeExporter:
  enabled: false  # Disable by default for dev
  service:
    type: ClusterIP
    port: 9100

# Kube State Metrics Configuration (optional for K8s metrics)
kubeStateMetrics:
  enabled: false  # Disable by default for dev
  service:
    type: ClusterIP
    port: 8080

# Redis Exporter Configuration (optional for Redis metrics)
redisExporter:
  enabled: false  # Disable by default for dev
  service:
    type: ClusterIP
    port: 9121

# RBAC Configuration
rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Network Policies
networkPolicy:
  enabled: true
  allowedNamespaces:
    - default
    - suma-android
    - suma-ecommerce
    - suma-office
    - suma-pmo
    - suma-chat
    - elasticsearch
    - kibana
    - redis

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Global Ingress Configuration (optional - services use their own ingress)
ingress:
  enabled: false  # Disabled - using per-service ingress instead
  className: nginx
  annotations: {}
  hosts: []
  tls: []

# Certificate Configuration
certificate:
  enabled: false  # Disabled for dev - services handle their own certs
  certificates: []

# ConfigMap for Prometheus and Grafana Dashboards
configMap:
  prometheusRules:
    enabled: true
  dashboards:
    enabled: true