apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines

---
# Service accounts used by Tekton components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-webhook
  namespace: tekton-pipelines

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-pipelines-controller
  template:
    metadata:
      labels:
        app: tekton-pipelines-controller
    spec:
      serviceAccountName: tekton-pipelines-controller
      # If your registry requires credentials, create an imagePullSecret
      # and add it here (example in README):
      # imagePullSecrets:
      #   - name: quay-reg
      containers:
        - name: tekton-pipelines-controller
          image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.63.0
          args:
            - "--entrypoint-image=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.63.0"
            - "--nop-image=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.63.0"
            - "--shell-image=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/shell:v0.63.0"
            - "--shell-image-win=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/shell:v0.63.0"
            - "--sidecarlogresults-image=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.63.0"
            - "--workingdirinit-image=gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.63.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
