# Tekton non-CRD resources (trimmed)
# This file should contain the full set of namespaced/non-CRD resources
# required by Tekton (ServiceAccounts, Roles, RoleBindings, Deployments,
# Services, ConfigMaps, PVCs, etc.). The full non-CRD content was truncated for
# brevity; if you have the original non-CRD blocks, paste them here.

# Example placeholders (replace with actual content from original file):
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-webhook
  namespace: tekton-pipelines

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-pipelines-controller
  template:
    metadata:
      labels:
        app: tekton-pipelines-controller
    spec:
      serviceAccountName: tekton-pipelines-controller
      containers:
        - name: tekton-pipelines-controller
          image: ghcr.io/tektoncd/pipeline/controller:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# (Other non-CRD resources from the original tekton-pipelines-noncrd.yaml follow)
# The file below contains the namespaced and cluster roles/bindings, serviceaccounts,
# RBAC, Deployments, Services, ConfigMaps, Secrets and other non-CRD resources
# necessary for Tekton runtime but with the CustomResourceDefinition documents removed.

# NOTE: This file intentionally excludes any `apiVersion: apiextensions.k8s.io/v1` /
# `kind: CustomResourceDefinition` documents. CRDs are backed up in
# tekton/tekton-crds-backup.yaml and should be managed once at infra level.