apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma-chat
  namespace: suma-chat
  labels:
    app: suma-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suma-chat
  template:
    metadata:
      labels:
        app: suma-chat
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - "sh"
            - "-c"
            - "until nc -z redis 6379; do echo 'waiting for redis'; sleep 2; done"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - suma-chat
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: suma-chat
          image: suma-chat:latest # replace with your image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: http
          envFrom:
            - configMapRef:
                name: suma-chat-config
            - secretRef:
                name: suma-chat-secret
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sleep 30"
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000