apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: suma-chat-hpa
  namespace: suma-chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: suma-chat
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
