apiVersion: v1
kind: Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines

---
# Service accounts used by Tekton components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-controller
  apiVersion: v1
  kind: Namespace
  metadata:
    name: tekton-pipelines

  ---
  ---
  # ServiceAccounts used by Tekton components
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: tekton-pipelines-controller
    namespace: tekton-pipelines

  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: tekton-pipelines-webhook
    namespace: tekton-pipelines

  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: tekton-triggers-controller
    namespace: tekton-pipelines

  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: tekton-triggers-webhook
    namespace: tekton-pipelines

  ---
  # Minimal Deployment for Tekton Pipelines controller (standardized image)
  # Note: Keep imagePullSecrets configured in the cluster if your nodes need
  # authenticated access to quay/ghcr/gcr. See README.md for instructions.
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: tekton-pipelines-controller
    template:
      metadata:
        labels:
          app: tekton-pipelines-controller
      spec:
        serviceAccountName: tekton-pipelines-controller
        # Uncomment and set the name of an imagePullSecret if needed:
        # imagePullSecrets:
        #   - name: quay-reg
        containers:
          - name: tekton-pipelines-controller
            image: quay.io/tektoncd/pipeline/cmd/controller:v1.5.0
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"