apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-timeout-minutes: "60"
  default-service-account: "default"
  default-managed-by-label-value: "tekton-pipelines"
  default-cloud-events-sink: ""
  default-task-run-workspace-binding: ""
  default-max-matrix-combinations-count: "256"
  default-forbidden-env: ""
  default-affinity-assistant-pod-template: ""
  default-node-selector: ""
  default-tolerations: ""
  default-runtime-class: ""
  default-pod-template: ""
  default-apicoverage-check: "true"
  default-keep-pod-on-cancel: "false"
  default-enable-api-fields: "stable"
  default-send-cloudevents-for-runs: "false"
  default-verification-no-match-policy: "ignore"
  default-enable-provenance-in-status: "true"
  default-result-extraction-method: "termination-message"
  default-max-result-size: "4096"
  default-enforce-nonfalsified-provenance: "false"
  default-set-security-context: "false"
  default-security-context: ""
  default-disable-affinity-assistant: "false"
  default-disable-creds-init: "false"
  default-running-in-environment-with-injected-sidecars: "true"
  default-require-git-ssh-secret-known-hosts: "false"
  default-enable-git-resolver: "false"
  default-enable-hub-resolver: "false"
  default-trusted-resources-verification-no-match-policy: "ignore"
  default-trusted-resources-verified-annotations: "true"
  default-enable-cel-in-whenexpression: "false"
  default-enable-step-actions: "false"
