apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: tekton-pipelines
spec:
  containers:
  - name: registry
    image: registry:2
    ports:
    - containerPort: 5000
    env:
    - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
      value: /var/lib/registry
    volumeMounts:
    - name: registry-storage
      mountPath: /var/lib/registry
  volumes:
  - name: registry-storage
    emptyDir: {}