{
 "title": "🛡️ Ingress Nginx Monitoring",
 "tags": [
  "ingress-nginx",
  "api",
  "kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🔄 Controller Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ingress-nginx\"}",
     "legendFormat": "Health Check"
    }
   ]
  },
  {
   "title": "🔒 SSL Certificates by Domain",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ssl_certificate_info",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "📊 Request Methods by Domain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m])) by (host, method)",
     "legendFormat": "{{host}} - {{method}}"
    }
   ]
  },
  {
   "title": "🌐 Domains & Prefix Paths Handled by Ingress (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{service=\"suma-ecommerce-api-service\"}[5m])) by (host, path, method)",
     "legendFormat": "{{host}} - {{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "⚡ Requests Per Second (RPS) by Domain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "⏱️ Average Request Duration by Domain",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (host, le))",
     "legendFormat": "95th percentile - {{host}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (host, le))",
     "legendFormat": "50th percentile - {{host}}"
    }
   ]
  },
  {
   "title": "📈 Total Requests Over Time by Domain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}