apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suma-office.fullname" . }}-config
  labels:
    {{- include "suma-office.labels" . | nindent 4 }}
data:
  timezone: {{ .Values.config.timezone }}
  custom.ini: |
    upload_max_filesize = {{ .Values.config.maxFileSize }}
    post_max_size = {{ .Values.config.maxFileSize }}
    max_execution_time = {{ .Values.config.maxExecutionTime }}
    memory_limit = {{ .Values.config.memoryLimit }}