apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Urutan apply resources untuk menghindari dependency error (namespace, cert-manager, dll. dulu)
resources:
  # 1. Vendors (cert-manager, ingress-nginx, metrics-server)
  - vendors/cert-manager.yaml
  - vendors/ingress-nginx.yaml
  - vendors/metrics-server.yaml

  # 2. Certs (issuer dan certificate setelah cert-manager)
  - certs/clusterissuer-selfsigned.yaml
  - certs/api-public-cert.yaml

  # 3. Infra pendukung (monitoring)
  - monitoring/namespace.yaml
  - monitoring/configmap.yaml
  - monitoring/rbac.yaml
  - monitoring/pvc.yaml
  - monitoring/pdb.yaml
  - monitoring/deployment.yaml
  - monitoring/service.yaml
  - monitoring/networkpolicy.yaml
  - monitoring/ingress.yaml

  # 4. Service aplikasi (suma-chat)
  - suma-chat/namespace.yaml
  - suma-chat/secret.yaml
  - suma-chat/certificate.yaml
  - suma-chat/configmap.yaml
  - suma-chat/redis-deployment.yaml
  - suma-chat/redis-service.yaml
  - suma-chat/service.yaml
  - suma-chat/deployment.yaml
  - suma-chat/hpa.yaml
  - suma-chat/networkpolicy.yaml
  - suma-chat/poddisruptionbudget.yaml
  - suma-chat/ingress.yaml

  - ngrok/configmap.yaml
  - ngrok/secret.yaml
  - ngrok/deployments.yaml
  - ngrok/service.yaml

  # 5. Dashboard ArgoCD
  - argocd/dashboard-ingress.yaml

  # 6. Tekton Deploy (non-CRD resources)
  # Use CRD-less variants so ArgoCD does not continuously manage CRDs from this app.
  - tekton/00-minimal-noncrd.yaml
  - tekton/triggers-noncrd.yaml
  - tekton/dashboard.yaml
  - tekton/ingress-dashboard.yaml
  - tekton/ingress-eventlistener.yaml
  - tekton/pvc.yaml
  - tekton/rbac.yaml
  - tekton/triggers-clusterrole.yaml
  - tekton/triggers-sa-default.yaml
  # Additional config and debug manifests added for cluster startup
  - tekton/config-defaults-v0.63.yaml
  - tekton/clusterrole-configmaps.yaml
  - tekton/config-logging.yaml
  - tekton/config-observability.yaml
  - tekton/config-tracing.yaml
  - tekton/config-wait-exponential-backoff.yaml
  - tekton/config-events.yaml
  - tekton/config-spire.yaml
  - tekton/config-feature-flags.yaml

  # 7. Tekton Pipelines dan Triggers (suma-ecommerce)
  - tekton/suma-ecommerce/git-clone-task.yaml
  - tekton/suma-ecommerce/kaniko-task.yaml
  - tekton/suma-ecommerce/pipeline.yaml
  - tekton/suma-ecommerce/triggerbinding.yaml
  - tekton/suma-ecommerce/triggertemplate.yaml
  - tekton/suma-ecommerce/update-deployment-task.yaml
  - tekton/suma-ecommerce/eventlistener.yaml
patches:
  - path: tekton/patches/patch-el-eventlistener-payload-validation.yaml
    target:
      kind: EventListener
      name: suma-ecommerce-release-listener