apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Urutan apply resources untuk menghindari dependency error (namespace, cert-manager, dll. dulu)
resources:
  # 1. Vendors (cert-manager, ingress-nginx, metrics-server)
  - vendors/

  # 2. Certs (issuer dan certificate setelah cert-manager)
  - certs/

  # 3. ArgoCD dan Tekton
  - argocd/
  # - tekton/

  # 4. Infra pendukung (redis, elasticsearch, kibana, monitoring)
  # - redis/
  # - elasticsearch/
  # - kibana/
  - monitoring/

  # 5. Aplikasi utama
  # - suma-android/
  - suma-chat/
  - ngrok/
  # - suma-ecommerce/
  # - suma-office/
  # - suma-office-general/
  # - suma-pmo/

