apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kibana.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.config.elasticsearchHosts }}
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: {{ .Values.config.elasticsearchCertificateAuthorities }}
            - name: XPACK_SECURITY_ENABLED
              value: {{ .Values.security.enabled | quote }}
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kibana.fullname" . }}-encryption-key
                  key: encryptionKey
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          {{- if .Values.security.tls.enabled }}
          volumeMounts:
            - name: certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.security.tls.enabled }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "kibana.fullname" . }}-certs
      {{- end }}