apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kibana.fullname" . }}-encryption-key
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
  encryptionKey: {{ .Values.encryptionKey | b64enc }}