{{- if and .Values.security.tls.enabled .Values.security.tls.certificates.selfsigned.enabled }}
---
# Self-signed Issuer for Kibana internal TLS
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kibana.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
# Certificate for Kibana
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kibana.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kibana.fullname" . }}-certs
  issuerRef:
    name: {{ include "kibana.fullname" . }}-selfsigned
    kind: Issuer
  commonName: {{ include "kibana.fullname" . }}
  dnsNames:
    - {{ include "kibana.fullname" . }}
    - {{ include "kibana.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "kibana.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kibana.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  privateKey:
    algorithm: RSA
    size: 2048
{{- end }}
