apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: "./Dockerfile"
    - name: CONTEXT
      type: string
      default: "."
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: ghcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --cache=true