apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: suma-ecommerce-pipeline
spec:
  params:
    - name: release-tag
      type: string
    - name: repo-name
      type: string
      default: "suma-ecommerce"
    - name: commit-sha
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: checkout-code
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/AHMnesia/$(params.repo-name).git"
        - name: revision
          value: $(params.commit-sha)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image
      taskRef:
        name: kaniko
      runAfter: [checkout-code]
      params:
        - name: IMAGE
          value: "ahmnesia/$(params.repo-name):$(params.release-tag)"
        - name: DOCKERFILE
          value: "./dockerfile"
        - name: CONTEXT
          value: "./"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: update-deployment
      taskRef:
        name: update-deployment
      runAfter: [build-image]
      params:
        - name: deployment-file
          value: "k8s/suma-ecommerce/deployment.yaml"
        - name: image-name
          value: "ahmnesia/$(params.repo-name):$(params.release-tag)"
      workspaces:
        - name: source
          workspace: shared-workspace
