apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - encryption-secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - ingress.yaml