apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suma-chat.fullname" . }}
  labels:
    {{- include "suma-chat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "suma-chat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "suma-chat.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "suma-chat.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.config.port | quote }}
            - name: NODE_ENV
              value: {{ .Values.config.nodeEnv }}
            - name: TZ
              value: {{ .Values.config.timezone }}
            - name: API_URL
              value: {{ .Values.config.apiUrl }}
            - name: SOCKET_PATH
              value: {{ .Values.config.socketPath }}
            - name: REDIS_HOST
              value: {{ include "suma-chat.fullname" . }}-redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6