{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "suma-pmo.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace | default "suma-pmo" }}
  labels:
    {{- include "suma-pmo.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className | default "nginx" }}
  {{- if .tls }}
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ include "suma-pmo.fullname" $ }}
            port:
              number: {{ $.Values.service.port | default 8000 }}
      {{- end }}
{{- end }}
{{- end }}
