apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Values.namespace | default "redis" }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
