replicaCount: 1

namespace: kibana

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.7.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Kibana Configuration
config:
  elasticsearchHosts: "https://suma-platform-elasticsearch:9200"
  elasticsearchCertificateAuthorities: "/usr/share/kibana/config/certs/ca.crt"

# Security
security:
  enabled: true
  tls:
    enabled: true
    certificates:
      selfsigned:
        enabled: true

# Encryption key for session storage
encryptionKey: "0a462f8c21b5ee192ad995af9b914bec4f22e97def54ad697e04960adfc295d8"

# Network Policy
networkPolicy:
  enabled: true
  allowedNamespaces:
    - ingress-nginx
    - nginx-system
    - elasticsearch

# Service
service:
  type: ClusterIP
  port: 5601

# Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
  hosts:
    - host: kibana.suma-honda.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.suma-honda.local

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false

certificate:
  enabled: true
  certificates:
    - name: kibana-certs
      secretName: kibana-certs
      issuerRef:
        name: suma-ca-issuer
        kind: ClusterIssuer
      dnsNames:
        - kibana
        - kibana.kibana
        - kibana.kibana.svc
        - kibana.kibana.svc.cluster.local