apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
  namespace: suma-chat
type: Opaque
data:
  # Base64 encoded ngrok auth token
  # Replace with your actual token: echo -n "your_ngrok_token" | base64
  NGROK_AUTHTOKEN: Mm84azZudFplYm5pRjlmSTlPc2wxWFFHN0loXzZaak5oN1c4UUY0RTM0YkpHSDdhQQ==