apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: suma-chat
spec:
  selector:
    app: ngrok
  ports:
  - name: web
    port: 4040
    targetPort: 4040
    protocol: TCP
  type: ClusterIP