apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: suma-android-api-hpa
  namespace: suma-android
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: suma-android-api
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
