replicaCount: 2
revisionHistoryLimit: 3

namespace: suma-android

image:
  repository: suma-android-api
  tag: latest
  pullPolicy: Never

command: ['php', 'artisan', 'serve', '--host=0.0.0.0', '--port=8000']
workingDir: /var/www/html

service:
  type: ClusterIP
  port: 8000

env:
  APP_ENV: "production"
  APP_DEBUG: "false"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
    ephemeral-storage: "500Mi"
  limits:
    memory: "1Gi"
    cpu: "800m"
    ephemeral-storage: "2Gi"

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 30

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

persistence:
  enabled: true
  volumes:
    - name: api-pvc
      size: 1Gi
      mountPath: /var/www/html/storage/app
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      annotations:
        description: "Persistent storage for application data/uploads"
    - name: uploads-pvc
      size: 500Mi
      mountPath: /var/www/html/public/uploads
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      annotations:
        description: "Storage for uploaded assets and static files"

ingress:
  enabled: true
  className: nginx
  hosts:
    - name: local
      host: suma-android.local
      tls: true
      tlsSecret: suma-android-tls
      annotations:
        kubernetes.io/ingress.class: "nginx"
      paths:
        - path: /
          pathType: Prefix
    - name: api
      host: api.suma-honda.id
      tls: true
      tlsSecret: api-suma-honda-id-tls
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        nginx.ingress.kubernetes.io/proxy-body-size: "10m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
      paths:
        - path: /android(/|$)(.*)
          pathType: ImplementationSpecific

networkPolicy:
  enabled: true
  allowedNamespaces:
    - ingress-nginx
    - nginx-system

podDisruptionBudget:
  enabled: true
  minAvailable: 1

certificate:
  enabled: true
  certificates:
    - name: suma-android-local-tls
      secretName: suma-android-tls
      issuerRef:
        name: selfsigned-cluster-issuer
        kind: ClusterIssuer
      dnsNames:
        - suma-android.local

podAnnotations: {}
