{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-alertmanager
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      serviceAccountName: {{ include "monitoring.serviceAccountName" . }}
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-storage
              mountPath: /alertmanager
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: alertmanager-config
          configMap:
            name: {{ include "monitoring.fullname" . }}-alertmanager
        - name: alertmanager-storage
          {{- if .Values.alertmanager.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "monitoring.fullname" . }}-alertmanager
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}