{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "monitoring.fullname" . }}-ingress
  namespace: {{ .Values.namespace | default "monitoring" }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: monitoring
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  {{- toYaml .Values.networkPolicy.allowedNamespaces | nindent 18 }}
{{- end }}
