{{- if .Values.podDisruptionBudget.enabled }}
{{- range .Values.podDisruptionBudget.budgets }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "monitoring" }}
  labels:
    {{- include "monitoring.labels" $ | nindent 4 }}
    component: {{ .component }}
spec:
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .app }}
{{- end }}
{{- end }}
