apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
  ports:
    - name: web
      port: {{ .Values.prometheus.service.port | default 9090 }}
      targetPort: {{ .Values.prometheus.service.port | default 9090 }}
      protocol: TCP
  selector:
    app: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type | default "ClusterIP" }}
  ports:
    - name: web
      port: {{ .Values.grafana.service.port | default 3000 }}
      targetPort: {{ .Values.grafana.service.port | default 3000 }}
      protocol: TCP
  selector:
    app: grafana
