{
 "title": "🌐 Global Services Overview",
 "tags": [
  "overview",
  "global",
  "all-services"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🌐 Combined Service Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\"ingress-nginx-health|elasticsearch-health|kibana-health|suma-ecommerce-api-health|suma-office-api-health|suma-office-general-api-health|suma-pmo-api-health|suma-android-api-health|suma-chat-health|redis-health\"}, \"job\", \"$1\", \"job\", \"(.*)-health\") or up{job=~\"prometheus|blackbox\"}"
    }
   ]
  },
  {
   "title": "🖥️ CPU Core Used / Total (est) • CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))",
     "legendFormat": "Total Core"
    },
    {
     "expr": "sum(sum by (instance, cpu) (1 - avg by (instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))))",
     "legendFormat": "Used Core (est)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "📦 RAM Used / Total (GB) • Memory Usage (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "Total RAM (GB)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "Used RAM (GB)"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory Usage %"
    }
   ]
  },
  {
   "title": "📈 Total Requests 🟢 [2xx,3xx,4xx] Over Time by Domain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (host, path) (rate(nginx_ingress_controller_requests{status=~\"2..\", host!=\"monitoring.suma-honda.local\"}[5m]))",
     "legendFormat": "(2xx) {{host}}{{path}}"
    },
    {
     "expr": "sum by (host, path) (rate(nginx_ingress_controller_requests{status=~\"3..\", host!=\"monitoring.suma-honda.local\"}[5m]))",
     "legendFormat": "(3xx) {{host}}{{path}}"
    },
    {
     "expr": "sum by (host, path) (rate(nginx_ingress_controller_requests{status=~\"4..\", host!=\"monitoring.suma-honda.local\"}[5m]))",
     "legendFormat": "(4xx) {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "🏃 Pod Status by Namespace",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by (namespace) (container_start_time_seconds{namespace=~\"ingress-nginx|suma-ecommerce|suma-office|suma-office-general|suma-pmo|suma-android|monitoring|elasticsearch|kibana|suma-chat|redis\", pod!=\"\"})"
    }
   ]
  },
  {
   "title": "📈 Total Requests 🔴 [5xx] Over Time by Domain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (host, path) (rate(nginx_ingress_controller_requests{status=~\"5..\", host!=\"monitoring.suma-honda.local\"}[5m]))",
     "legendFormat": "{{host}}{{path}}"
    }
   ]
  }
 ]
}